spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cadastrodb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: senha123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true