version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_cadastro
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: cadastrodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./wait-for-it.sh:/app/wait-for-it.sh
    entrypoint: ["/app/wait-for-it.sh", "postgres:5432", "--", "java", "-jar", "app.jar"]

volumes:
  postgres_data:
    driver: local