version: "3.8"

services:
  # Serviço do banco de dados PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres_cadastro
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: cadastrodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Serviço para rodar as migrações do Flyway
  flyway:
    image: flyway/flyway:latest
    container_name: flyway_migrations
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    command:
      - -url=jdbc:postgresql://postgres:5432/cadastrodb
      - -user=postgres
      - -password=senha123
      - -connectRetries=10
      - migrate

  # Serviço da aplicação (Back-end Spring Boot)
  app:
    build: .
    container_name: cadastro_backend
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cadastrodb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: senha123
      SPRING_FLYWAY_ENABLED: "false" # Flyway será gerenciado pelo serviço flyway
    volumes:
      - ./wait-for-it.sh:/app/wait-for-it.sh
    entrypoint: ["/app/wait-for-it.sh", "postgres:5432", "--", "java", "-jar", "app.jar"]

volumes:
  postgres_data:
    driver: local
